Revert "Build(deps): Bump redis from 4.2.2 to 4.2.3"
This reverts commit f31de2fa200e58ca25b3f9d03631287fb82dc104.

This is causing `NoMethodError (undefined method `bytesize' for nil:NilClass)` in the anonymous cache. More investigation required