FIX: correctly guard for missing close method (#32760)
`?.close()` is an unsafe pattern

```
test = {}
test?.close()
￼VM363:1 Uncaught TypeError: test?.close is not a function
    at <anonymous>:1:7
```