FIX: add finished to modal animateBackdropOpacity promise (#34879)
Fixes an error when closing modals on mobile because a promise wasn't
being returned

`Uncaught (in promise) TypeError: promise.then is not a function`

<img width="2060" height="846" alt="image"
src="https://github.com/user-attachments/assets/ffb54160-d3d8-4fd1-a358-3b150b99b5c7"
/>