FIX: allow editing post content in penalty modal (#44051)
Changed postEdit from getter-only to tracked property to allow editing
the textarea without console errors.
Error: `Uncaught TypeError: Cannot set property postEdit of
#<PenalizeUser> which has only a getter`