FIX: switch to toSorted to avoid mutating original emoji array (#37450)
Related to
https://meta.discourse.org/t/admin-config-emoji-non-responsive-locks-up/394857

After uploading an emoji I can see an error on the index, 

>  Error: Assertion Failed: You attempted to update `_value` on
`TrackedStorageImpl`, but it had already been used previously in the
same computation.
Attempting to update a value after using it in a computation can cause
logical errors,
infinite revalidation bugs, and performance issues, and is not
supported.
 
`sort` mutates the array in-place, `toSorted` returns a new array