FIX: Lightbox failed to start in components due to null imgEl element. (#36310)
#36156 introduced `const imgEl = el.tagName === "IMG" ? el :
el.querySelector("img");` to the lightbox component to capture the image
element on the page.

However, when it comes to applying the lightbox to an element without
`<img>` , i.e., discourse solved, backquote, activity page, etc. The
`imgEl` will turn into null, and the following `data.origSrc =
imgEl.getAttribute("data-orig-src");` will result in `Uncaught
TypeError: can't access property "getAttribute", imgEl is null`,
preventing the lightbox from starting properly.

This commit add a safety check when `imgEl` is used, and add fallback
logic to null if the `<img>` element doesn't exist.

Before:
<img width="1603" height="845" alt="image"
src="https://github.com/user-attachments/assets/6e588a00-53bf-410a-bbac-3f24a820d494"
/>

After:
<img width="1603" height="848" alt="image"
src="https://github.com/user-attachments/assets/07868ade-0e1b-43d2-83cc-c2fec3da9109"
/>