FIX: allow editing post content in penalty modal [backport 2026.7] (#44055)
Backport of #44051 to release/2026.7.

---

Changed postEdit from getter-only to tracked property to allow editing
the textarea without console errors.
Error: `Uncaught TypeError: Cannot set property postEdit of
#<PenalizeUser> which has only a getter`

Co-authored-by: Amanda Alves Branquinho <amanda@discourse.org>